name: Build and Test Suite

on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  build-tests:
    name: Test and Build
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
        toolchain:
          - stable
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Build tests
        run: cargo test --locked --all --release --features "json-tests" --verbose --no-run

      - name: Run tests for ${{ matrix.platform }}
        run: cargo test --locked --all --release --features "json-tests" --verbose
