name: Build and Test Suite

on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  build-tests:
    name: Test and Build
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@1.75.0

      - name: Build
        run: cargo build --locked --all --release --verbose

      - name: Run tests
        run: cargo test --locked --all --release --verbose
