name: Check

on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@1.75.0

      - name: Run cargo check
        run: cargo check --locked --all

      - name: Run validate chainspecs
        run: |
          cargo build --locked --release -p chainspec
          for spec in crates/ethcore/res/chainspec/*.json crates/ethcore/res/chainspec/test/*.json; do
            ./target/release/chainspec "$spec"
          done
